server:
  port: 8761
spring:
  application:
    name: naming-service
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    #essas configraões devem ser retiradas em produção
