server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/book_service
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
      
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    url: jdbc:postgresql://localhost:5432/
    schemas: book_service
    user: postgres
    password: postgres
  sleuth:
    sampler:
      probability: 1.0 #vai grvar 100% do log 
springdoc:
  show-actuator: true
  api-docs:
    path: book-service/v3/api-docs
    #configuração para roteamento do swagger no gateway